### PR TITLE
[baxter_sim_hardware] Add baxter_sim_io as run_depend

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
which is used in https://github.com/RethinkRobotics/baxter_simulator/blob/master/baxter_sim_hardware%2Flaunch%2Fbaxter_sdk_control.launch#L48

**Comment by davetcoleman** [comment]
+1

**Comment by IanTheEngineer** [comment]
This change looks good to me. @wkentaro if you retarget it at `development`, I'll approve and merge

**Comment by wkentaro** [comment]
changed.

**Comment by davetcoleman** [comment]
Also when this is merged, can it be cherry-picked to ``kinetic-devel``?

**Comment by IanTheEngineer** [comment]
I see 13 additional commits here. Can you add your one commit onto the head of `development` please? Thanks!

**Comment by wkentaro** [comment]
Fixed.

**Comment by IanTheEngineer** [comment]
Wonderful. Thanks for the PR and update @wkentaro

**Pull request merged**
