### PR TITLE
[baxter_simulator] Depends on joint_state_controller

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by davetcoleman** [comment]
+1

**Comment by IanTheEngineer** [comment]
Sorry to let this sit for so long, @wkentaro. I agree that this change should be made. The issue is only that the merge was requested in the `master` branch, rather than `development`. This change is currently present in the `kinetic-devel` branch, which is our Kinetic feature branch off of `development`.

**Comment by wkentaro** [comment]
So should I change the base branch from `master` to `development`?

**Comment by IanTheEngineer** [comment]
That would be great, thank you. I'm working on a CONTRIBUTING.md to explain the process better for  contributors.

**Comment by wkentaro** [comment]
Updated.

**Comment by IanTheEngineer** [comment]
Same deal as the other PR, 13 too many commits here. Can you pop your new commit onto the head of `development` please? Thanks!

**Comment by wkentaro** [comment]
Hmm. I think you can do it by GitHub gui.

**Comment by wkentaro** [comment]
Fixed.

**Comment by IanTheEngineer** [comment]
Seems that this is now in conflict with the already-merged `baxter_sim_hardware/package.xml`, would you mind a quick rebase? Otherwise, I can help out. Thank you :)

**Comment by wkentaro** [comment]
Resolved.

**Comment by IanTheEngineer** [comment]
Thank you for working with me here, @wkentaro. Your contributions are greatly appreciated! :1st_place_medal:

**Comment by wkentaro** [comment]
Thank you.

**Pull request merged**
