### PR TITLE
[baxters_sim_hardware | baxter_sim_kinematics] modified to work baxter_world.launch properly when arg electric_gripper is false

### PR DESCRIPTION
**Pull request by knorth55**
Require: https://github.com/RethinkRobotics/baxter_common/pull/79
- `grav_[right|left]_name` and `right|left]_tip_name` can be changed for other gripper usage because these `param` was fixed so that we could not modify it easily.
- baxter xacro modified in https://github.com/RethinkRobotics/baxter_common/pull/79 so that gripper is no more loaded to gazebo when you give arg `[right|left]_electric_gripper:=false`
  gazebo_default
  gazebo_untuck

### CODE REVIEW

**Comment by knorth55** [comment]
@IanTheEngineer can you review this?

**Comment by knorth55** [comment]
ping

**Comment by IanTheEngineer** [comment]
resolved by https://github.com/RethinkRobotics/baxter_simulator/pull/118 and https://github.com/RethinkRobotics/baxter_common/pull/90

**Comment by knorth55** [comment]
Thank you.

**Pull request closed without merging**
